title: Demo Just the Docs 24 lutego
description: Practicing the Just the Docs theme!
theme: just-the-docs

url: https://https://kinrap.github.io/DemoJtD/

aux_links:
  Template Repository: https://github.com/KinRap/DemoJtD
